apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: traefik
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: traefik
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=hoks.io
        - --provider=google
        - --registry=txt
        - --txt-owner-id=my-identifier
